sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
 - pip install markdown
 - pip install rcslice
 - pip install cyclic
script: 
 - python -m mdx_include.test.test

