sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to install dependencies
install:
 - pip install markdown cyclic rcslice
script: 
 - python -m mdx_include.test.test

